name: Deploy to server

on:
  push:
    branches: [pipeline]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: cuvar/blog
          path: ./src
      - name: Use Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Deno build
        run: deno run -A https://deno.land/x/lume@v1.9.1/ci.ts
      - name: Copy to production via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATEKEY }}
          source: .
          target: .
          debug: true
          rm: true
